export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_ERROR = "FETCH_ARTICLES_ERROR";
export const FETCH_ARTICLES_LOADING = "FETCH_ARTICLES_LOADING";

export const REMOVE_ARTICLE_SUCCESS = "REMOVE_ARTICLE_SUCCESS";
export const REMOVE_ARTICLE_ERROR = "REMOVE_ARTICLE_ERROR";
export const REMOVE_ARTICLE_LOADING = "REMOVE_ARTICLE_LOADING";
